version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: vulnapp-db
    restart: always
    environment:
      POSTGRES_DB: vulnappdb
      POSTGRES_USER: vulnuser
      POSTGRES_PASSWORD: vulnpass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
