spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vulnappdb
    username: vulnuser
    password: vulnpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: uninpahu
  sql:
    init:
      mode: always
